atlantis:
  orgAllowlist: github.com/jmorgan415/*
  logLevel: "info"

  github:
    user: "override-in-secret"
  vcsSecretName: "wiz-atlantis"

  # serviceAccount:
  #   annotations:
  #     eks.amazonaws.com/role-arn: arn:aws:iam::457661787930:role/457661787930-pse-infra-atlantis-manager

  # image:
  #   repository: 984186218765.dkr.ecr.us-east-2.amazonaws.com/atlantis
  #   tag: v0.19.9
  #   pullPolicy: IfNotPresent

  ## Use Server Side Repo Config,
  ## ref: https://www.runatlantis.io/docs/server-side-repo-config.html
  repoConfig: |
   ---
   repos:
   - id: github.com/jmorgan415/safeflight-hg-school
     apply_requirements: [approved, mergeable]
     allowed_overrides: [workflow, apply_requirements]
     # allow_custom_workflows defines whether this repo can define its own
     # workflows. If false (default), the repo can only use server-side defined
     # workflows.
     allow_custom_workflows: true
     # delete_source_branch_on_merge: true
  #  workflows:
  #    default:
  #      plan:
  #        steps:
  #        - init
  #        - plan:
  #            extra_args: ["-var-file", ./config.tfvars"]
  #      apply:
  #        steps:
  #        - run: terraform${ATLANTIS_TERRAFORM_VERSION} apply -no-color -parallelism=50 $PLANFILE
  #    ws:
  #      plan:
  #        steps:
  #        - run: terraform${ATLANTIS_TERRAFORM_VERSION} init -input=false -no-color
  #        - run: terraform${ATLANTIS_TERRAFORM_VERSION} workspace select -no-color ${WORKSPACE} || terraform${ATLANTIS_TERRAFORM_VERSION} workspace new ${WORKSPACE} && terraform${ATLANTIS_TERRAFORM_VERSION} workspace select -no-color ${WORKSPACE}
  #        - run: terraform${ATLANTIS_TERRAFORM_VERSION} plan -var-file=./config.tfvars -input=false -refresh -no-color -parallelism=50 -out $PLANFILE
  #      apply:
  #        steps:
  #        - run: terraform${ATLANTIS_TERRAFORM_VERSION} apply -no-color -parallelism=50 $PLANFILE

  # service:
  #   type: NodePort
  #   port: 80
  #   targetPort: 4141

  ingress:
    enabled: false
  #   ingressClassName: nginx
  #   annotations:
  #     nginx.ingress.kubernetes.io/rewrite-target: /
  #     cert-manager.io/cluster-issuer: letsencrypt-production
  #     external-dns.alpha.kubernetes.io/hostname: "atlantis.wizdemo.co"
  #   paths:
  #   - path: /
  #     pathType: Prefix
  #     backend:
  #       service:
  #         name: atlantis
  #         port:
  #           number: 80
  #   hosts:
  #     - host: atlantis.wizdemo.co
  #       paths: ["/"]
  #       service: atlantis
  #   tls:
  #     - hosts:
  #       - atlantis.wizdemo.co
  #       secretName: letsencrypt-production

  # dataStorage: 15Gi

  # resources:
  #   requests:
  #     memory: 8Gi
  #     cpu: 2
  #   limits:
  #     memory: 8Gi
  #     cpu: 2

  # extraVolumeMounts:
  #   - name: gcp-creds
  #     mountPath: /gcp.json
  #     subPath: gcp.json
  # extraVolumes:
  #   - name: gcp-creds
  #     secret:
  #       secretName: atlantis-vcs
