apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: atlantis-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be Secrets Manager
      region: us-west-2   # Region where the secret is.
      auth:
        jwt:
          serviceAccountRef:
            name: atlantis
